name: Docker Image CI

on:
  push:
    branches: ["main"]

env:
  REGISTRY: vumana24
  IMAGE_NAME: kubelabs_publicapi2
  OPS_BRANCH: main
  OPS_REPO: vumana24/ops
  VERSION: 5.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          fetch-depth: 0
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          build-args: |
            APP_ENV= ${{ secrets.APP_ENV_PROD }}
        
      # - name: Run test
      #  run: docker run --rm --name api -p 3000:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest  

  deploy:
    name: OPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
        name: Checkout OPS code
        with:
          repository: ${{ env.OPS_REPO }}
          ssh-key: ${{ secrets.OPS_TOKEN }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"
      - name: Update Kubernetes resources
        run: |
          cd public-api/overlays/production
          kustomize edit set image KUSTOMIZE-DEFINED=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          # Optional
          kustomize build . > app.yaml
          cat app.yaml
      - name: Commit files
        run: |
          git config --local user.email "deploy-bot@stotylabs.dev"
          git config --local user.name "Storylabs deploy-Bot"
          git add .
          git commit -am "New image version, branch: main, tag: ${{ env.VERSION }}"
          git push --force origin